spring:
    #JDBC
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    #elasticsearch
    data:
        elasticsearch:
              properties:
                    path:
                      data: target/elasticsearch/data #elasticsearch数据存储目录
                      logs: target/elasticsearch/log #elasticsearch日志存储目录
                    transport:
                      tcp:
                        connect_timeout: 120s
#Mybatis
mybatis:
      type-aliases-package: com.example.blogs.model
      mapper-locations: classpath:mybatis-mappers/*Mapper.xml
