spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
      type-aliases-package: com.example.blogs.model
      mapper-locations: classpath:mybatis-mappers/*Mapper.xml
